# Site Config
site_name: Ayuda Paso Informática
site_description: Guía de Ayuda para las Reservas del Paso Informática USC
site_author: Paso Informática
site_url: https://ayuda.pasoinfo.xyz/
docs_dir: ayuda

# Dev
dev_addr: '127.0.0.1:8008'

# Repository
repo_name: Ayuda SiResU
repo_url: https://github.com/Paso-Informatica/Ayuda-SiResU
edit_uri: blob/master/ayuda/

# Copyright text in the footer
copyright: Paso Informática USC &copy; 2021-2022

# Customization
extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://reservas.pasoinfo.xyz
      name: Reservas Paso Informática
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/pasoinformatica.2122
      name: Dános like en Instagram!
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pasoinformatica
      name: Síguenos en Twitter!
    - icon: fontawesome/brands/tiktok
      link: https://tiktok.com/@pasoinformatica21
      name: También en TikTok!
  # disqus: "kodular-docs"
  generator: false

# Material theme for MkDocs : https://github.com/squidfunk/mkdocs-material/
theme:
  name: 'material'
  language: es
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Cambia al modo oscuro
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Cambia al modo claro
  logo: 'assets/logo.png'
  favicon: 'assets/favicon.ico'
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - git-revision-date-localized:
      type: date
      timezone: Europe/Madrid
      locale: es
      fallback_to_build_date: true

markdown_extensions:
  - codehilite
  - def_list
  # Markdown extensions: https://python-markdown.github.io/extensions/
  - admonition
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  # PyMdown Extensions
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

# Site navigation in the side bar
nav:
  - Reservas:
    - index.md
    - Proceso de Reserva: proceso.md
  - Administración:
    - admin/index.md
    - Permisos: admin/permisos.md
    - Superadmin:
      - admin/superadmin/index.md
      - Asignación de Permisos: admin/superadmin/asignacion.md
      - Gestión de Superadmins: admin/superadmin/superadmins.md
      - Registro de Acciones: admin/superadmin/registro.md
    - Eventos:
      - admin/eventos/index.md
    - Reservas:
      - admin/reservas/index.md
    - Ventas:
      - admin/ventas/index.md
    - Mesa:
      - admin/mesa/index.md
      - Gestión de Enlaces: admin/mesa/enlaces.md
      - Publicación de Mesas: admin/mesa/mesas.md
  - Soporte:
      - soporte/index.md
      - Política de Privacidad: soporte/privacidad.md
